Public Interface IConnection
    Event ReceiveMessage As EventHandler(Of ReceiveMessage)
    Event Disconnecting As EventHandler(Of EventArgs)
    Event Disconnect As EventHandler(Of DisconnectEventArgs)
    Event ReceiveAccess As EventHandler(Of AccessReceiveMessage)
    Event ReceiveAdd As EventHandler(Of AddReceiveMessage)
    Event ReceiveAutoText As EventHandler(Of AutoTextReceiveMessage)
    Event ReceiveBlockPlace As EventHandler(Of BlockPlaceReceiveMessage)
    Event ReceiveClear As EventHandler(Of ClearReceiveMessage)
    Event ReceiveCoin As EventHandler(Of CoinReceiveMessage)
    Event ReceiveCoinDoorPlace As EventHandler(Of CoinDoorPlaceReceiveMessage)
    Event ReceiveCrown As EventHandler(Of CrownReceiveMessage)
    Event ReceiveFace As EventHandler(Of FaceReceiveMessage)
    Event ReceiveGiveFireWizard As EventHandler(Of GiveFireWizardReceiveMessage)
    Event ReceiveGiveGrinch As EventHandler(Of GiveGrinchReceiveMessage)
    Event ReceiveGiveWitch As EventHandler(Of GiveWitchReceiveMessage)
    Event ReceiveGiveWizard As EventHandler(Of GiveWizardReceiveMessage)
    Event ReceiveGodMode As EventHandler(Of GodModeReceiveMessage)
    Event ReceiveGroupDisallowedJoin As EventHandler(Of GroupDisallowedJoinReceiveMessage)
    Event ReceiveHideKey As EventHandler(Of HideKeyReceiveMessage)
    Event ReceiveInfo As EventHandler(Of InfoReceiveMessage)
    Event ReceiveInit As EventHandler(Of InitReceiveMessage)
    Event ReceivePotion As EventHandler(Of PotionReceiveMessage)
    Event ReceiveLabelPlace As EventHandler(Of LabelPlaceReceiveMessage)
    Event ReceiveLeft As EventHandler(Of LeftReceiveMessage)
    Event ReceiveLostAccess As EventHandler(Of LostAccessReceiveMessage)
    Event ReceiveModMode As EventHandler(Of ModModeReceiveMessage)
    Event ReceiveMove As EventHandler(Of MoveReceiveMessage)
    Event ReceivePortalPlace As EventHandler(Of PortalPlaceReceiveMessage)
    Event ReceiveRefreshShop As EventHandler(Of RefreshShopReceiveMessage)
    Event ReceiveReset As EventHandler(Of ResetReceiveMessage)
    Event ReceiveSaveDone As EventHandler(Of SaveDoneReceiveMessage)
    Event ReceiveSay As EventHandler(Of SayReceiveMessage)
    Event ReceiveSayOld As EventHandler(Of SayOldReceiveMessage)
    Event ReceiveShowKey As EventHandler(Of ShowKeyReceiveMessage)
    Event ReceiveSilverCrown As EventHandler(Of SilverCrownReceiveMessage)
    Event ReceiveSoundPlace As EventHandler(Of SoundPlaceReceiveMessage)
    Event ReceiveTeleport As EventHandler(Of TeleportReceiveMessage)
    Event ReceiveUpdateMeta As EventHandler(Of UpdateMetaReceiveMessage)
    Event ReceiveUpgrade As EventHandler(Of UpgradeReceiveMessage)
    Event ReceiveWrite As EventHandler(Of WriteReceiveMessage)
    Event SendMessage As EventHandler(Of SendMessage)
    Event SendInit As EventHandler(Of Cancelable(Of InitSendMessage))
    Event SendInit2 As EventHandler(Of Cancelable(Of Init2SendMessage))
    Event SendBlockPlace As EventHandler(Of Cancelable(Of BlockPlaceSendMessage))
    Event SendCoindoorPlace As EventHandler(Of Cancelable(Of CoinDoorPlaceSendMessage))
    Event SendSoundPlace As EventHandler(Of Cancelable(Of SoundPlaceSendMessage))
    Event SendPortalPlace As EventHandler(Of Cancelable(Of PortalPlaceSendMessage))
    Event SendLabelPlace As EventHandler(Of Cancelable(Of LabelPlaceSendMessage))
    Event SendCoin As EventHandler(Of Cancelable(Of CoinSendMessage))
    Event SendPressRedKey As EventHandler(Of Cancelable(Of PressRedKeySendMessage))
    Event SendPressGreenKey As EventHandler(Of Cancelable(Of PressGreenKeySendMessage))
    Event SendPressBlueKey As EventHandler(Of Cancelable(Of PressBlueKeySendMessage))
    Event SendGetCrown As EventHandler(Of Cancelable(Of GetCrownSendMessage))
    Event SendTouchDiamond As EventHandler(Of Cancelable(Of TouchDiamondSendMessage))
    Event SendTouchCake As EventHandler(Of Cancelable(Of TouchCakeSendMessage))
    Event SendCompleteLevel As EventHandler(Of Cancelable(Of CompleteLevelSendMessage))
    Event SendGodMode As EventHandler(Of Cancelable(Of GodModeSendMessage))
    Event SendModMode As EventHandler(Of Cancelable(Of ModModeSendMessage))
    Event SendMove As EventHandler(Of Cancelable(Of MoveSendMessage))
    Event SendSay As EventHandler(Of Cancelable(Of SaySendMessage))
    Event SendAutoSay As EventHandler(Of Cancelable(Of AutoSaySendMessage))
    Event SendAccess As EventHandler(Of Cancelable(Of AccessSendMessage))
    Event SendChangeFace As EventHandler(Of Cancelable(Of ChangeFaceSendMessage))
    Event SendSaveWorld As EventHandler(Of Cancelable(Of SaveWorldSendMessage))
    Event SendChangeWorldName As EventHandler(Of Cancelable(Of ChangeWorldNameSendMessage))
    Event SendChangeWorldEditKey As EventHandler(Of Cancelable(Of ChangeWorldEditKeySendMessage))
    Event SendClearWorld As EventHandler(Of Cancelable(Of ClearWorldSendMessage))
    Event SendKillWorld As EventHandler(Of Cancelable(Of KillWorldSendMessage))
    Event SendPotion As EventHandler(Of Cancelable(Of PotionSendMessage))

    ReadOnly Property WorldID As String
    ReadOnly Property Connected As Boolean

    Function ConnectAsync(username As String, password As String, id As String) As task
    Sub Send(message As SendMessage)
    Sub Close()
End Interface
