Public Interface IMessageManager
    Event OnReceiveMessage As EventHandler(Of ReceiveMessage)
    Event OnDisconnect As EventHandler(Of EventArgs)
    Event OnReceiveAccess As EventHandler(Of AccessReceiveMessage)
    Event OnReceiveAdd As EventHandler(Of AddReceiveMessage)
    Event OnReceiveAutoText As EventHandler(Of AutoTextReceiveMessage)
    Event OnReceiveBlockPlace As EventHandler(Of BlockPlaceReceiveMessage)
    Event OnReceiveClear As EventHandler(Of ClearReceiveMessage)
    Event OnReceiveCoin As EventHandler(Of CoinReceiveMessage)
    Event OnReceiveCoinDoorPlace As EventHandler(Of CoinDoorPlace_ReceiveMessage)
    Event OnReceiveCrown As EventHandler(Of CrownReceiveMessage)
    Event OnReceiveFace As EventHandler(Of FaceReceiveMessage)
    Event OnReceiveGiveFireWizard As EventHandler(Of GiveFireWizardReceiveMessage)
    Event OnReceiveGiveGrinch As EventHandler(Of GiveGrinchReceiveMessage)
    Event OnReceiveGiveWitch As EventHandler(Of GiveWitchReceiveMessage)
    Event OnReceiveGiveWizard As EventHandler(Of GiveWizardReceiveMessage)
    Event OnReceiveGodMode As EventHandler(Of GodModeReceiveMessage)
    Event OnReceiveGroupDisallowedJoin As EventHandler(Of GroupDisallowedJoinReceiveMessage)
    Event OnReceiveHideKey As EventHandler(Of HideKeyReceiveMessage)
    Event OnReceiveInfo As EventHandler(Of InfoReceiveMessage)
    Event OnReceiveInit As EventHandler(Of InitReceiveMessage)
    Event OnReceiveLabelPlace As EventHandler(Of LabelPlaceReceiveMessage)
    Event OnReceiveLeft As EventHandler(Of LeftReceiveMessage)
    Event OnReceiveLostAccess As EventHandler(Of LostAccessReceiveMessage)
    Event OnReceiveModMode As EventHandler(Of ModModeReceiveMessage)
    Event OnReceiveMove As EventHandler(Of MoveReceiveMessage)
    Event OnReceivePortalPlace As EventHandler(Of PortalPlaceReceiveMessage)
    Event OnReceiveRefreshShop As EventHandler(Of RefreshShopReceiveMessage)
    Event OnReceiveReset As EventHandler(Of ResetReceiveMessage)
    Event OnReceiveSaveDone As EventHandler(Of SaveDoneReceiveMessage)
    Event OnReceiveSay As EventHandler(Of SayReceiveMessage)
    Event OnReceiveSayOld As EventHandler(Of SayOld_ReceiveMessage)
    Event OnReceiveShowKey As EventHandler(Of ShowKeyReceiveMessage)
    Event OnReceiveSilverCrown As EventHandler(Of SilverCrownReceiveMessage)
    Event OnReceiveSoundPlace As EventHandler(Of SoundPlaceReceiveMessage)
    Event OnReceiveTeleport As EventHandler(Of TeleportReceiveMessage)
    Event OnReceiveUpdateMeta As EventHandler(Of UpdateMetaReceiveMessage)
    Event OnReceiveUpgrade As EventHandler(Of UpgradeReceiveMessage)
    Event OnReceiveWrite As EventHandler(Of WriteReceiveMessage)
    Event OnSendMessage As EventHandler(Of SendMessage)
    Event OnSendInit As EventHandler(Of SendEventArgs(Of InitSendMessage))
    Event OnSendInit2 As EventHandler(Of SendEventArgs(Of Init2SendMessage))
    Event OnSendBlockPlace As EventHandler(Of SendEventArgs(Of BlockPlaceSendMessage))
    Event OnSendCoindoorPlace As EventHandler(Of SendEventArgs(Of CoinDoorPlaceSendMessage))
    Event OnSendSoundPlace As EventHandler(Of SendEventArgs(Of SoundPlaceSendMessage))
    Event OnSendPortalPlace As EventHandler(Of SendEventArgs(Of PortalPlaceSendMessage))
    Event OnSendLabelPlace As EventHandler(Of SendEventArgs(Of LabelPlaceSendMessage))
    Event OnSendCoin As EventHandler(Of SendEventArgs(Of CoinSendMessage))
    Event OnSendPressRedKey As EventHandler(Of SendEventArgs(Of PressRedKeySendMessage))
    Event OnSendPressGreenKey As EventHandler(Of SendEventArgs(Of PressGreenKeySendMessage))
    Event OnSendPressBlueKey As EventHandler(Of SendEventArgs(Of PressBlueKeySendMessage))
    Event OnSendGetCrown As EventHandler(Of SendEventArgs(Of GetCrownSendMessage))
    Event OnSendTouchDiamond As EventHandler(Of SendEventArgs(Of TouchDiamondSendMessage))
    Event OnSendCompleteLevel As EventHandler(Of SendEventArgs(Of CompleteLevelSendMessage))
    Event OnSendGodMode As EventHandler(Of SendEventArgs(Of GodModeSendMessage))
    Event OnSendModMode As EventHandler(Of SendEventArgs(Of ModModeSendMessage))
    Event OnSendMove As EventHandler(Of SendEventArgs(Of MoveSendMessage))
    Event OnSendSay As EventHandler(Of SendEventArgs(Of SaySendMessage))
    Event OnSendAutoSay As EventHandler(Of SendEventArgs(Of AutoSaySendMessage))
    Event OnSendAccess As EventHandler(Of SendEventArgs(Of AccessSendMessage))
    Event OnSendChangeFace As EventHandler(Of SendEventArgs(Of ChangeFaceSendMessage))
    Event OnSendSaveWorld As EventHandler(Of SendEventArgs(Of SaveWorldSendMessage))
    Event OnSendChangeWorldName As EventHandler(Of SendEventArgs(Of ChangeWorldNameSendMessage))
    Event OnSendChangeWorldEditKey As EventHandler(Of SendEventArgs(Of ChangeWorldEditKeySendMessage))
    Event OnSendClearWorld As EventHandler(Of SendEventArgs(Of ClearWorldSendMessage))
    Event OnSendKillWorld As EventHandler(Of SendEventArgs(Of KillWorldSendMessage))
End Interface
