'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EEService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserData", [Namespace]:="http://schemas.datacontract.org/2004/07/EEService"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserData
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FTBreakerWinsField As UShort
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GroupIDField As Short
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private YoScrollWinsField As UShort
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FTBreakerWins() As UShort
            Get
                Return Me.FTBreakerWinsField
            End Get
            Set
                If (Me.FTBreakerWinsField.Equals(value) <> true) Then
                    Me.FTBreakerWinsField = value
                    Me.RaisePropertyChanged("FTBreakerWins")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GroupID() As Short
            Get
                Return Me.GroupIDField
            End Get
            Set
                If (Me.GroupIDField.Equals(value) <> true) Then
                    Me.GroupIDField = value
                    Me.RaisePropertyChanged("GroupID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property YoScrollWins() As UShort
            Get
                Return Me.YoScrollWinsField
            End Get
            Set
                If (Me.YoScrollWinsField.Equals(value) <> true) Then
                    Me.YoScrollWinsField = value
                    Me.RaisePropertyChanged("YoScrollWins")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EEService.IEES")>  _
    Public Interface IEES
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/CheckLicense", ReplyAction:="http://tempuri.org/IEES/CheckLicenseResponse")>  _
        Function CheckLicense(ByVal username As String, ByVal authKey As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/CheckLicense", ReplyAction:="http://tempuri.org/IEES/CheckLicenseResponse")>  _
        Function CheckLicenseAsync(ByVal username As String, ByVal authKey As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetSetting", ReplyAction:="http://tempuri.org/IEES/GetSettingResponse")>  _
        Function GetSetting(ByVal key As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetSetting", ReplyAction:="http://tempuri.org/IEES/GetSettingResponse")>  _
        Function GetSettingAsync(ByVal key As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetSetting", ReplyAction:="http://tempuri.org/IEES/SetSettingResponse")>  _
        Sub SetSetting(ByVal key As String, ByVal value As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetSetting", ReplyAction:="http://tempuri.org/IEES/SetSettingResponse")>  _
        Function SetSettingAsync(ByVal key As String, ByVal value As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetFact", ReplyAction:="http://tempuri.org/IEES/SetFactResponse")>  _
        Sub SetFact(ByVal factID As String, ByVal factGroup As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetFact", ReplyAction:="http://tempuri.org/IEES/SetFactResponse")>  _
        Function SetFactAsync(ByVal factID As String, ByVal factGroup As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/RemoveFact", ReplyAction:="http://tempuri.org/IEES/RemoveFactResponse")>  _
        Sub RemoveFact(ByVal factID As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/RemoveFact", ReplyAction:="http://tempuri.org/IEES/RemoveFactResponse")>  _
        Function RemoveFactAsync(ByVal factID As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetFacts", ReplyAction:="http://tempuri.org/IEES/GetFactsResponse")>  _
        Function GetFacts(ByVal factGroup As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetFacts", ReplyAction:="http://tempuri.org/IEES/GetFactsResponse")>  _
        Function GetFactsAsync(ByVal factGroup As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetPlayerData", ReplyAction:="http://tempuri.org/IEES/GetPlayerDataResponse")>  _
        Function GetPlayerData(ByVal username As String) As EEService.UserData
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetPlayerData", ReplyAction:="http://tempuri.org/IEES/GetPlayerDataResponse")>  _
        Function GetPlayerDataAsync(ByVal username As String) As System.Threading.Tasks.Task(Of EEService.UserData)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetPlayerDatas", ReplyAction:="http://tempuri.org/IEES/GetPlayerDatasResponse")>  _
        Function GetPlayerDatas(ByVal usernames() As String) As EEService.UserData()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetPlayerDatas", ReplyAction:="http://tempuri.org/IEES/GetPlayerDatasResponse")>  _
        Function GetPlayerDatasAsync(ByVal usernames() As String) As System.Threading.Tasks.Task(Of EEService.UserData())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetPlayerDataRange", ReplyAction:="http://tempuri.org/IEES/GetPlayerDataRangeResponse")>  _
        Function GetPlayerDataRange(ByVal offset As UInteger, ByVal limit As UInteger, ByVal orderBy As String) As EEService.UserData()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/GetPlayerDataRange", ReplyAction:="http://tempuri.org/IEES/GetPlayerDataRangeResponse")>  _
        Function GetPlayerDataRangeAsync(ByVal offset As UInteger, ByVal limit As UInteger, ByVal orderBy As String) As System.Threading.Tasks.Task(Of EEService.UserData())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetPlayerDataGroupID", ReplyAction:="http://tempuri.org/IEES/SetPlayerDataGroupIDResponse")>  _
        Sub SetPlayerDataGroupID(ByVal username As String, ByVal groupID As Short)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetPlayerDataGroupID", ReplyAction:="http://tempuri.org/IEES/SetPlayerDataGroupIDResponse")>  _
        Function SetPlayerDataGroupIDAsync(ByVal username As String, ByVal groupID As Short) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetPlayerDataYoScrollWins", ReplyAction:="http://tempuri.org/IEES/SetPlayerDataYoScrollWinsResponse")>  _
        Sub SetPlayerDataYoScrollWins(ByVal username As String, ByVal yoScrollWins As UShort)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetPlayerDataYoScrollWins", ReplyAction:="http://tempuri.org/IEES/SetPlayerDataYoScrollWinsResponse")>  _
        Function SetPlayerDataYoScrollWinsAsync(ByVal username As String, ByVal yoScrollWins As UShort) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetPlayerDataFTBreakerWins", ReplyAction:="http://tempuri.org/IEES/SetPlayerDataFTBreakerWinsResponse")>  _
        Sub SetPlayerDataFTBreakerWins(ByVal username As String, ByVal ftBreakerWins As UShort)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IEES/SetPlayerDataFTBreakerWins", ReplyAction:="http://tempuri.org/IEES/SetPlayerDataFTBreakerWinsResponse")>  _
        Function SetPlayerDataFTBreakerWinsAsync(ByVal username As String, ByVal ftBreakerWins As UShort) As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IEESChannel
        Inherits EEService.IEES, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EESClient
        Inherits System.ServiceModel.ClientBase(Of EEService.IEES)
        Implements EEService.IEES
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CheckLicense(ByVal username As String, ByVal authKey As String) As Boolean Implements EEService.IEES.CheckLicense
            Return MyBase.Channel.CheckLicense(username, authKey)
        End Function
        
        Public Function CheckLicenseAsync(ByVal username As String, ByVal authKey As String) As System.Threading.Tasks.Task(Of Boolean) Implements EEService.IEES.CheckLicenseAsync
            Return MyBase.Channel.CheckLicenseAsync(username, authKey)
        End Function
        
        Public Function GetSetting(ByVal key As String) As String Implements EEService.IEES.GetSetting
            Return MyBase.Channel.GetSetting(key)
        End Function
        
        Public Function GetSettingAsync(ByVal key As String) As System.Threading.Tasks.Task(Of String) Implements EEService.IEES.GetSettingAsync
            Return MyBase.Channel.GetSettingAsync(key)
        End Function
        
        Public Sub SetSetting(ByVal key As String, ByVal value As String) Implements EEService.IEES.SetSetting
            MyBase.Channel.SetSetting(key, value)
        End Sub
        
        Public Function SetSettingAsync(ByVal key As String, ByVal value As String) As System.Threading.Tasks.Task Implements EEService.IEES.SetSettingAsync
            Return MyBase.Channel.SetSettingAsync(key, value)
        End Function
        
        Public Sub SetFact(ByVal factID As String, ByVal factGroup As String) Implements EEService.IEES.SetFact
            MyBase.Channel.SetFact(factID, factGroup)
        End Sub
        
        Public Function SetFactAsync(ByVal factID As String, ByVal factGroup As String) As System.Threading.Tasks.Task Implements EEService.IEES.SetFactAsync
            Return MyBase.Channel.SetFactAsync(factID, factGroup)
        End Function
        
        Public Sub RemoveFact(ByVal factID As String) Implements EEService.IEES.RemoveFact
            MyBase.Channel.RemoveFact(factID)
        End Sub
        
        Public Function RemoveFactAsync(ByVal factID As String) As System.Threading.Tasks.Task Implements EEService.IEES.RemoveFactAsync
            Return MyBase.Channel.RemoveFactAsync(factID)
        End Function
        
        Public Function GetFacts(ByVal factGroup As String) As String() Implements EEService.IEES.GetFacts
            Return MyBase.Channel.GetFacts(factGroup)
        End Function
        
        Public Function GetFactsAsync(ByVal factGroup As String) As System.Threading.Tasks.Task(Of String()) Implements EEService.IEES.GetFactsAsync
            Return MyBase.Channel.GetFactsAsync(factGroup)
        End Function
        
        Public Function GetPlayerData(ByVal username As String) As EEService.UserData Implements EEService.IEES.GetPlayerData
            Return MyBase.Channel.GetPlayerData(username)
        End Function
        
        Public Function GetPlayerDataAsync(ByVal username As String) As System.Threading.Tasks.Task(Of EEService.UserData) Implements EEService.IEES.GetPlayerDataAsync
            Return MyBase.Channel.GetPlayerDataAsync(username)
        End Function
        
        Public Function GetPlayerDatas(ByVal usernames() As String) As EEService.UserData() Implements EEService.IEES.GetPlayerDatas
            Return MyBase.Channel.GetPlayerDatas(usernames)
        End Function
        
        Public Function GetPlayerDatasAsync(ByVal usernames() As String) As System.Threading.Tasks.Task(Of EEService.UserData()) Implements EEService.IEES.GetPlayerDatasAsync
            Return MyBase.Channel.GetPlayerDatasAsync(usernames)
        End Function
        
        Public Function GetPlayerDataRange(ByVal offset As UInteger, ByVal limit As UInteger, ByVal orderBy As String) As EEService.UserData() Implements EEService.IEES.GetPlayerDataRange
            Return MyBase.Channel.GetPlayerDataRange(offset, limit, orderBy)
        End Function
        
        Public Function GetPlayerDataRangeAsync(ByVal offset As UInteger, ByVal limit As UInteger, ByVal orderBy As String) As System.Threading.Tasks.Task(Of EEService.UserData()) Implements EEService.IEES.GetPlayerDataRangeAsync
            Return MyBase.Channel.GetPlayerDataRangeAsync(offset, limit, orderBy)
        End Function
        
        Public Sub SetPlayerDataGroupID(ByVal username As String, ByVal groupID As Short) Implements EEService.IEES.SetPlayerDataGroupID
            MyBase.Channel.SetPlayerDataGroupID(username, groupID)
        End Sub
        
        Public Function SetPlayerDataGroupIDAsync(ByVal username As String, ByVal groupID As Short) As System.Threading.Tasks.Task Implements EEService.IEES.SetPlayerDataGroupIDAsync
            Return MyBase.Channel.SetPlayerDataGroupIDAsync(username, groupID)
        End Function
        
        Public Sub SetPlayerDataYoScrollWins(ByVal username As String, ByVal yoScrollWins As UShort) Implements EEService.IEES.SetPlayerDataYoScrollWins
            MyBase.Channel.SetPlayerDataYoScrollWins(username, yoScrollWins)
        End Sub
        
        Public Function SetPlayerDataYoScrollWinsAsync(ByVal username As String, ByVal yoScrollWins As UShort) As System.Threading.Tasks.Task Implements EEService.IEES.SetPlayerDataYoScrollWinsAsync
            Return MyBase.Channel.SetPlayerDataYoScrollWinsAsync(username, yoScrollWins)
        End Function
        
        Public Sub SetPlayerDataFTBreakerWins(ByVal username As String, ByVal ftBreakerWins As UShort) Implements EEService.IEES.SetPlayerDataFTBreakerWins
            MyBase.Channel.SetPlayerDataFTBreakerWins(username, ftBreakerWins)
        End Sub
        
        Public Function SetPlayerDataFTBreakerWinsAsync(ByVal username As String, ByVal ftBreakerWins As UShort) As System.Threading.Tasks.Task Implements EEService.IEES.SetPlayerDataFTBreakerWinsAsync
            Return MyBase.Channel.SetPlayerDataFTBreakerWinsAsync(username, ftBreakerWins)
        End Function
    End Class
End Namespace
